project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - R/generating_materials/qmds/*.qmd   # all generated lessons

website:
  title: "Moje statistika"
  navbar:
    left:
      - href: index.html
        text: Ãšvod
  sidebar:
    style: floating
    search: true
    contents: auto

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true